Build vbd only when xen is enabled
vbd was added for xen based VMs since
bdee00fac9b4 ("Disk reading interface for Xen based VMs and example")
and should be built only when xen is enabled, otherwise there would not be
necessary xen headers and cause the following failure.

xen_private.h:38:10: fatal error: xenctrl.h: No such file or directory

Signed-off-by: He Zhe <zhe.he@windriver.com>